Repository Diptenusarkar/Website-Template, pull requests merged in 2021-10, with the labels that each got.

#1 commited my quote site
  Quote-site/index.html
  Quote-site/quotes.js
  Quote-site/style.css
Labels: hacktoberfest-accepted

#2 Update README.md with more concise and clear language.
  README.md
Labels: documentation

#4 Fixed typos in README.md
  README.md
Labels: documentation

#6 Added react template
  react-template/.gitignore
  react-template/README.md
  react-template/package-lock.json
  react-template/package.json
  react-template/public/favicon.ico
  react-template/public/index.html
  react-template/public/logo192.png
  react-template/public/logo512.png
  react-template/public/manifest.json
  react-template/public/robots.txt
  react-template/src/App.js
  react-template/src/App.test.js
  react-template/src/Dashboard.jsx
  react-template/src/index.js
  react-template/src/reportWebVitals.js
  react-template/src/setupTests.js
Labels: enhancement, hacktoberfest-accepted
