Repository Diptenusarkar/Website-Template, pull requests merged in 2022-10, with the labels that each got.

#12 added StickyNavbar
  StickyNavbar/background.jpg
  StickyNavbar/index.html
  StickyNavbar/style.css
Labels: hacktoberfest-accepted

#13 Add Next.JS template
  nextjs-template/.eslintrc.json
  nextjs-template/.gitignore
  nextjs-template/README.md
  nextjs-template/next.config.js
  nextjs-template/package.json
  nextjs-template/pages/_app.jsx
  nextjs-template/pages/api/hello.js
  nextjs-template/pages/index.jsx
  nextjs-template/public/favicon.ico
  nextjs-template/public/vercel.svg
  nextjs-template/styles/Home.module.css
  nextjs-template/styles/globals.css
  nextjs-template/yarn.lock
Labels: hacktoberfest-accepted

#14 added HamBurgerPage file
  HamBurgerPage/index.html
  HamBurgerPage/screenshots/Capture1.PNG
  HamBurgerPage/screenshots/Capture2.PNG
  HamBurgerPage/style.css
Labels: hacktoberfest-accepted

#18 GRADIENT GENERATOR
  Gradient-Generator/style.css/index.html
  Gradient-Generator/style.css/script.js
  Gradient-Generator/style.css/style.css
Labels: hacktoberfest-accepted

#19 Software Portfolio
  .replit
  portfolio/index.html
  portfolio/main.js
  portfolio/style.css
  replit.nix
Labels: hacktoberfest-accepted

#20 Express Template
  Express Template/.gitignore
  Express Template/README.md
  Express Template/package-lock.json
  Express Template/package.json
  Express Template/routes/about.js
  Express Template/routes/contact.js
  Express Template/routes/home.js
  Express Template/server.js
  Express Template/static/images/image.png
  Express Template/static/style/style.css
  Express Template/views/about.pug
  Express Template/views/contact.pug
  Express Template/views/home.pug
  Express Template/views/index.pug
  Express Template/views/navbar.pug
Labels: hacktoberfest-accepted

#23 Profile Hover Cards
  ProfileHover/dynamo.jpg
  ProfileHover/index.html
  ProfileHover/mortal.jpg
  ProfileHover/style.css
  ProfileHover/ujjwal.jpg
Labels: hacktoberfest-accepted

#25 Glass Like Effect - Glassomorphism
  Glassomorphism/index.html
  Glassomorphism/style.css
Labels: hacktoberfest-accepted

#26 Created SECURITY.MD file
  SECURITY.md
Labels: documentation

#27 Searchbar
  Searchbar/data/users.json
  Searchbar/index.html
  Searchbar/script/script.js
  Searchbar/style/style.css
Labels: hacktoberfest-accepted

#30 docs: Added link to index in README.md
  README.md
Labels: documentation

#31 Update style.css
  Quote-site/style.css
Labels: hacktoberfest-accepted

#32 Expense Tracker🌟
  expense-tracker-react/.gitignore
  expense-tracker-react/README.md
  expense-tracker-react/package-lock.json
  expense-tracker-react/package.json
  expense-tracker-react/public/favicon.ico
  expense-tracker-react/public/index.html
  expense-tracker-react/public/logo192.png
  expense-tracker-react/public/logo512.png
  expense-tracker-react/public/manifest.json
  expense-tracker-react/public/robots.txt
  expense-tracker-react/src/App.js
  expense-tracker-react/src/components/Chart/Chart.css
  expense-tracker-react/src/components/Chart/Chart.js
  expense-tracker-react/src/components/Chart/ChartBar.css
  expense-tracker-react/src/components/Chart/ChartBar.js
  expense-tracker-react/src/components/Expenses/ExpenseDate.css
  expense-tracker-react/src/components/Expenses/ExpenseDate.js
  expense-tracker-react/src/components/Expenses/ExpenseItem.css
  expense-tracker-react/src/components/Expenses/ExpenseItem.js
  expense-tracker-react/src/components/Expenses/Expenses.css
  expense-tracker-react/src/components/Expenses/Expenses.js
  expense-tracker-react/src/components/Expenses/ExpensesChart.js
  expense-tracker-react/src/components/Expenses/ExpensesFilter.css
  expense-tracker-react/src/components/Expenses/ExpensesFilter.js
  expense-tracker-react/src/components/Expenses/ExpensesList.css
  expense-tracker-react/src/components/Expenses/ExpensesList.js
  expense-tracker-react/src/components/NewExpense/ExpenseForm.css
  expense-tracker-react/src/components/NewExpense/ExpenseForm.js
  expense-tracker-react/src/components/NewExpense/NewExpense.css
  expense-tracker-react/src/components/NewExpense/NewExpense.js
  expense-tracker-react/src/components/UI/Card.css
  expense-tracker-react/src/components/UI/Card.js
  expense-tracker-react/src/index.css
  expense-tracker-react/src/index.js
Labels: hacktoberfest-accepted

#33 fixed: Link for next.js in index
  README.md
Labels: documentation

#51 Night mode Toggler template
  NightMode/index.html
Labels: hacktoberfest-accepted

#55 Add files via upload
  sign up form/background.jpg
  sign up form/signup.html
  sign up form/user.png
Labels: hacktoberfest-accepted

#58 HACKTOBERFEST-2022
  BOOKING TEMPLATE/index.html
  BOOKING TEMPLATE/jscript.js
  BOOKING TEMPLATE/style.css
Labels: hacktoberfest-accepted

#52 Added Login Page With Side Image Template
  Login Page/Demo1.jpg
  Login Page/index.html
  Login Page/style.css
  Login Page/validation.js
Labels: hacktoberfest-accepted

#65 registration and login form
  Registration-login form/img/fb.jpg
  Registration-login form/img/githublogo.png
  Registration-login form/img/ista.png
  Registration-login form/img/link.png
  Registration-login form/img/sset.jpg
  Registration-login form/index.html
  Registration-login form/style2.css
Labels: hacktoberfest-accepted

#67 Update index.html
  Website Under construction/index.html
Labels: hacktoberfest-accepted

#70 rotating images gallery
  Rotating images/index.html
  Rotating images/rotate.js
  Rotating images/style2.css
Labels: hacktoberfest-accepted

#77 New 404 Page.
  404 Page V2/404.html
  404 Page V2/index.html
Labels: hacktoberfest-accepted

#81 Restaraunt Website
  Restaraunt Website/app.js
  Restaraunt Website/details.json
  Restaraunt Website/fonts.txt
  Restaraunt Website/index.html
  Restaraunt Website/style.css
Labels: hacktoberfest-accepted

#85 travel blog full mobile view responsive
  Travel Blog/index.html
  Travel Blog/style/dsky/main.css
Labels: hacktoberfest-accepted

#93 added transformation to 360 degrees to social icons when hovered
  portfolio/style.css
Labels: hacktoberfest-accepted

#95 Added the Mansory Layout Project #94
  Mansory Layout/index.html
  Mansory Layout/style.css
Labels: hacktoberfest-accepted

#96 form & cards design improved in Travel blog
  Travel Blog/index.html
  Travel Blog/style/dsky/main.css
Labels: hacktoberfest-accepted

#100 expanding-gallery-cards
  Expanding gallery cards/card1.jfif
  Expanding gallery cards/card2.jfif
  Expanding gallery cards/card3.jfif
  Expanding gallery cards/card4.jfif
  Expanding gallery cards/card5.jfif
  Expanding gallery cards/index.html
  Expanding gallery cards/script.js
  Expanding gallery cards/style.css
Labels: hacktoberfest-accepted

#104 Contributing.md file
  contributing.md
Labels: hacktoberfest-accepted

#103 This is a Payment form template.
  Payment-Gateway -template/README.md
  Payment-Gateway -template/payment.css
  Payment-Gateway -template/payment_form.html
Labels: hacktoberfest-accepted

#102 Adding Flexbox Templates
  Flexbox Templates/Flexbox-1/flexbox_1.html
  Flexbox Templates/Flexbox-2/flexbox.html
  Flexbox Templates/Flexbox-2/img1.jpg
  Flexbox Templates/Flexbox-2/img2.jpg
  Flexbox Templates/Flexbox-2/img3.jpg
  Flexbox Templates/Flexbox-2/img4.jpg
  Flexbox Templates/Flexbox-2/img5.jpg
  Flexbox Templates/Flexbox-2/img6.jpg
  Flexbox Templates/Flexbox-3/flexbox.html
Labels: hacktoberfest-accepted

#101 adding education site landing page
  edu-fun/.vscode/settings.json
  edu-fun/css/animate.css
  edu-fun/css/bootstrap.min.css
  edu-fun/css/custom.css
  edu-fun/css/flashy.min.css
  edu-fun/css/flaticon.css
  edu-fun/css/font-awesome.min.css
  edu-fun/css/magnific-popup.css
  edu-fun/css/pogo-slider.min.css
  edu-fun/css/responsive.css
  edu-fun/css/responsiveslides.css
  edu-fun/css/style.css
  edu-fun/css/timeline.css
  edu-fun/fonts/Flaticon.eot
  edu-fun/fonts/Flaticon.svg
  edu-fun/fonts/Flaticon.ttf
  edu-fun/fonts/Flaticon.woff
  edu-fun/fonts/FontAwesome.otf
  edu-fun/fonts/fontawesome-webfont.eot
  edu-fun/fonts/fontawesome-webfont.svg
  edu-fun/fonts/fontawesome-webfont.ttf
  edu-fun/fonts/fontawesome-webfont.woff
  edu-fun/fonts/fontawesome-webfont.woff2
  edu-fun/images/banner_img.png
  edu-fun/images/footer_logo.png
  edu-fun/images/heading_main_border.png
  edu-fun/images/i1.png
  edu-fun/images/i2.png
  edu-fun/images/i3.png
  edu-fun/images/i4.png
  edu-fun/images/i5.png
  edu-fun/images/i6.png
  edu-fun/images/i7.png
  edu-fun/images/img10.png
  edu-fun/images/img2.png
  edu-fun/images/img6.png
  edu-fun/images/img7.png
  edu-fun/images/img8.png
  edu-fun/images/img9.png
  edu-fun/images/loader.gif
  edu-fun/images/logo.png
  edu-fun/images/p1.png
  edu-fun/images/p2.png
  edu-fun/images/p3.png
  edu-fun/images/search_icon.png
  edu-fun/index.html
  edu-fun/js/bootstrap.min.js
  edu-fun/js/custom.js
  edu-fun/js/form-validator.min.js
  edu-fun/js/images-loded.min.js
  edu-fun/js/isotope.min.js
  edu-fun/js/jquery.magnific-popup.min.js
  edu-fun/js/jquery.min.js
  edu-fun/js/jquery.pogo-slider.min.js
  edu-fun/js/popper.min.js
  edu-fun/js/slider-index.js
  edu-fun/js/smoothscroll.js
Labels: hacktoberfest-accepted

#118 Adding Grid Layout Templates
  Grid Layout Templates/Grid Layout using bootstrap/grid1.html
  Grid Layout Templates/Grid Layout using bootstrap/grid2.html
  Grid Layout Templates/Grid Layout using bootstrap/index.html
  Grid Layout Templates/Grid Layout using simple CSS/index.html
  Grid Layout Templates/Grid Layout using simple CSS/styles.css
Labels: hacktoberfest-accepted

#116 Add CSS card hovering effect with a TRIBUTE PAGE TEMPLATE
  CSS CARD HOVERING EFFECT/index.css
  CSS CARD HOVERING EFFECT/index.html
  Tribute Page Template/index.css
  Tribute Page Template/index.html
Labels: hacktoberfest-accepted

#113 Admin Dashboard Snippet
  Admin Dashboard/assets/adminIcon.png
  Admin Dashboard/assets/css/style.css
  Admin Dashboard/assets/js/index.js
  Admin Dashboard/index.html
  Admin Dashboard/preview/darkmode.png
  Admin Dashboard/preview/lightmode.png
  Admin Dashboard/readme.md
Labels: hacktoberfest-accepted

#110 404 Error pages website ui templates ( 3 Error pages )
  404 Error Pages v4/Error1.html
  404 Error Pages v4/Error2.html
  404 Error Pages v4/Error3.html
  404 Error Pages v4/Error3/error3.html
  404 Error Pages v4/Error3/style.css
  404 Error Pages v4/Images/error1.svg
  404 Error Pages v4/Images/error3.svg
  404 Error Pages v4/README.md
Labels: hacktoberfest-accepted

#109 add: 404 Page V3
  404 Page V3/css/style.css
  404 Page V3/img/ghost-img.png
  404 Page V3/index.html
  404 Page V3/js/main.js
  404 Page V3/js/scrollreveal.min.js
Labels: hacktoberfest-accepted

#108 Adding Interactive Tabs #106
  Interactive Tabs/css/style.css
  Interactive Tabs/index.html
Labels: hacktoberfest-accepted

#107 Ui Changes
  Travel Blog/style/dsky/main.css
Labels: hacktoberfest-accepted

#123 theme clock
  Theme Clock/index.html
  Theme Clock/script.js
  Theme Clock/style.css
Labels: hacktoberfest-accepted

#125 medical form changes
  Medical Template/index.html
  Medical Template/style/main.css
Labels: hacktoberfest-accepted

#131 APP LANDING PAGE
  App landing page/404.html
  App landing page/app/app-test.pdf
  App landing page/assets/bg-main-body.svg
  App landing page/assets/icon/cloud-arrow-down.svg
  App landing page/assets/image/social-card.png
  App landing page/assets/svg/online learning-cuate.svg
  App landing page/assets/svg/outer space-rafiki.svg
  App landing page/assets/svg/reading book-pana.svg
  App landing page/assets/svg/writing room-bro.svg
  App landing page/assets/vendor/font/bangla/ansi v1/li himaloy ansi v1 italic.ttf
  App landing page/assets/vendor/font/bangla/ansi v1/li himaloy ansi v1.ttf
  App landing page/assets/vendor/font/bangla/ansi v2/li himaloy ansi v2 italic.ttf
  App landing page/assets/vendor/font/bangla/ansi v2/li himaloy ansi v2.ttf
  App landing page/assets/vendor/font/bangla/readme.txt
  App landing page/assets/vendor/font/bangla/unicode/himaloy.ttf
  App landing page/assets/vendor/font/bangla/unicode/himaloy_italic.ttf
  App landing page/assets/vendor/font/bangla/unicode/li himaloy unicode italic.ttf
  App landing page/assets/vendor/font/bangla/unicode/li himaloy unicode.ttf
  App landing page/assets/vendor/font/english/no-font.htm
  App landing page/assets/vendor/javascript/no.app.js
  App landing page/assets/video/logo.mp4
  App landing page/favicon_io/about.txt
  App landing page/favicon_io/android-chrome-192x192.png
  App landing page/favicon_io/android-chrome-512x512.png
  App landing page/favicon_io/apple-touch-icon.png
  App landing page/favicon_io/favicon-16x16.png
  App landing page/favicon_io/favicon-32x32.png
  App landing page/favicon_io/favicon.ico
  App landing page/favicon_io/site.webmanifest
  App landing page/index.html
  App landing page/media/media320.css
  App landing page/media/media375.css
  App landing page/media/media425.css
  App landing page/media/media768.css
  App landing page/readme.md
  App landing page/style/main.css
Labels: hacktoberfest-accepted

#139 Adding Price Template
  Price Template/index.html
  Price Template/styles.css
Labels: hacktoberfest-accepted

#140 textutil application using reactjs.
  textutils/textutils/.gitignore
  textutils/textutils/.vscode/settings.json
  textutils/textutils/README.md
  textutils/textutils/package-lock.json
  textutils/textutils/package.json
  textutils/textutils/public/favicon.ico
  textutils/textutils/public/index.html
  textutils/textutils/public/logo192.png
  textutils/textutils/public/logo512.png
  textutils/textutils/public/manifest.json
  textutils/textutils/public/robots.txt
  textutils/textutils/src/App.css
  textutils/textutils/src/App.js
  textutils/textutils/src/App.test.js
  textutils/textutils/src/components/About.js
  textutils/textutils/src/components/Alert.js
  textutils/textutils/src/components/Navbar.js
  textutils/textutils/src/components/TextForm.js
  textutils/textutils/src/index.css
  textutils/textutils/src/index.js
  textutils/textutils/src/logo.svg
  textutils/textutils/src/reportWebVitals.js
  textutils/textutils/src/setupTests.js
Labels: enhancement, hacktoberfest-accepted

#133 Added my library management system
  Library_management/.gitignore
  Library_management/README.md
  Library_management/app.js
  Library_management/controllers/admin.js
  Library_management/controllers/customer.js
  Library_management/controllers/login.js
  Library_management/controllers/logout.js
  Library_management/controllers/signup.js
  Library_management/css/admin.css
  Library_management/css/customer.css
  Library_management/css/login.css
  Library_management/css/signup.css
  Library_management/images/Final_Logo_IIITL.png
  Library_management/images/background.jpg
  Library_management/images/banner.jpg
  Library_management/images/library.jpg
  Library_management/images/profile-pic.jpg
  Library_management/library_management_system.sql
  Library_management/models/bookModel.js
  Library_management/models/config.js
  Library_management/models/userModel.js
  Library_management/package-lock.json
  Library_management/package.json
  Library_management/validation_rules/rules.js
  Library_management/views/admin/books-add.ejs
  Library_management/views/admin/books-delete.ejs
  Library_management/views/admin/books-edit.ejs
  Library_management/views/admin/books-issue.ejs
  Library_management/views/admin/books-requested.ejs
  Library_management/views/admin/books.ejs
  Library_management/views/admin/change-password.ejs
  Library_management/views/admin/customers-add.ejs
  Library_management/views/admin/customers-delete.ejs
  Library_management/views/admin/customers-edit.ejs
  Library_management/views/admin/customers-profile.ejs
  Library_management/views/admin/customers.ejs
  Library_management/views/admin/home.ejs
  Library_management/views/admin/issued-books.ejs
  Library_management/views/admin/partials/navbar.html
  Library_management/views/admin/partials/sidebar.html
  Library_management/views/admin/partials/template.html
  Library_management/views/admin/profile-edit.ejs
  Library_management/views/admin/profile.ejs
  Library_management/views/customer/books-request.ejs
  Library_management/views/customer/books.ejs
  Library_management/views/customer/borrow-history.ejs
  Library_management/views/customer/borrowed-books.ejs
  Library_management/views/customer/change-password.ejs
  Library_management/views/customer/home.ejs
  Library_management/views/customer/partials/navbar.html
  Library_management/views/customer/partials/sidebar.html
  Library_management/views/customer/partials/template.html
  Library_management/views/customer/payment.ejs
  Library_management/views/customer/profile-edit.ejs
  Library_management/views/customer/profile.ejs
  Library_management/views/login.ejs
  Library_management/views/partials/footer.html
  Library_management/views/partials/header.html
  Library_management/views/signup.ejs
Labels: hacktoberfest-accepted

#151 Login template with React
  firebase-auth/README.md
  firebase-auth/package-lock.json
  firebase-auth/package.json
  firebase-auth/public/index.html
  firebase-auth/public/manifest.json
  firebase-auth/public/robots.txt
  firebase-auth/src/App.js
  firebase-auth/src/component/Navebar.jsx
  firebase-auth/src/images/undraw_secure_login_pdn4.png
  firebase-auth/src/images/undraw_welcome_cats_thqn.png
  firebase-auth/src/index.js
  firebase-auth/src/pages/Home.jsx
  firebase-auth/src/pages/Layout.jsx
  firebase-auth/src/pages/Login.jsx
  firebase-auth/src/pages/Register.jsx
  firebase-auth/src/reportWebVitals.js
  firebase-auth/src/setupTests.js
Labels: hacktoberfest-accepted

#153 Created About Me Template
  About Me Template/image/bg.jpg
  About Me Template/image/ppl.png
  About Me Template/index.html
  About Me Template/style.css
Labels: hacktoberfest-accepted

#163 Rock Paper Scissor game added
  Rock Paper Scissor/app.js
  Rock Paper Scissor/images/1.png
  Rock Paper Scissor/images/2.png
  Rock Paper Scissor/images/3.png
  Rock Paper Scissor/images/4.png
  Rock Paper Scissor/index.html
  Rock Paper Scissor/style.css
Labels: hacktoberfest-accepted

#162 Added Timeline Design Template
  Timeline Design/img/amazon.png
  Timeline Design/img/flipkart.png
  Timeline Design/img/google.png
  Timeline Design/img/tesla.png
  Timeline Design/img/toyota.png
  Timeline Design/img/youtube.png
  Timeline Design/index.html
  Timeline Design/style.css
Labels: hacktoberfest-accepted

#164 Adding Drum-kit application
  js 30 days/01 - JavaScript Drum Kit_sounds_boom.wav
  js 30 days/01 - JavaScript Drum Kit_sounds_clap (1).wav
  js 30 days/01 - JavaScript Drum Kit_sounds_clap.wav
  js 30 days/01 - JavaScript Drum Kit_sounds_hihat.wav
  js 30 days/01 - JavaScript Drum Kit_sounds_kick.wav
  js 30 days/01 - JavaScript Drum Kit_sounds_openhat.wav
  js 30 days/01 - JavaScript Drum Kit_sounds_ride.wav
  js 30 days/01 - JavaScript Drum Kit_sounds_snare.wav
  js 30 days/01 - JavaScript Drum Kit_sounds_tink.wav
  js 30 days/01 - JavaScript Drum Kit_sounds_tom.wav
  js 30 days/background.jpg
  js 30 days/indexstart.html
  js 30 days/style.css
Labels: hacktoberfest-accepted

#165 Countdown Timer added
  Countdown Timer/app.js
  Countdown Timer/images/README.md
  Countdown Timer/images/bg.mp4
  Countdown Timer/images/favicon.png
  Countdown Timer/index.html
  Countdown Timer/style.css
Labels: hacktoberfest-accepted

#166 Added a Login Page Template
  Login Page Template/index.html
  Login Page Template/style.css
Labels: hacktoberfest-accepted

#173 Added Parallex Web Design
  Parallax Design/Images/demo.jpg
  Parallax Design/Images/image1.jpg
  Parallax Design/Images/image2.jpg
  Parallax Design/Images/image3.jpg
  Parallax Design/ParallexEffect.css
  Parallax Design/ParallexEffect.html
Labels: hacktoberfest-accepted

#172 Added Form wave Project
  Form Wave Project/index.html
  Form Wave Project/script.js
  Form Wave Project/style.css
Labels: hacktoberfest-accepted

#171 Added Google Homepage Clone
  Google Homepage Clone/images/favicon.jpg
  Google Homepage Clone/images/logo.jpg
  Google Homepage Clone/index.html
  Google Homepage Clone/main.js
  Google Homepage Clone/style.css
Labels: hacktoberfest-accepted

#170 added Microsoft-clone
  Microsoft-clone/app.js
  Microsoft-clone/index.html
  Microsoft-clone/style.css
Labels: hacktoberfest-accepted

#169 Social Template
  Socials Template/img/bg.jpg
  Socials Template/index.html
  Socials Template/style.css
Labels: hacktoberfest-accepted

#168 Added Drum Kit application
  Drum Kit/images/crash.png
  Drum Kit/images/kick.png
  Drum Kit/images/snare.png
  Drum Kit/images/tom1.png
  Drum Kit/images/tom2.png
  Drum Kit/images/tom3.png
  Drum Kit/images/tom4.png
  Drum Kit/index.html
  Drum Kit/index.js
  Drum Kit/package.json
  Drum Kit/sandbox.config.json
  Drum Kit/sounds/crash.mp3
  Drum Kit/sounds/kick-bass.mp3
  Drum Kit/sounds/snare.mp3
  Drum Kit/sounds/tom-1.mp3
  Drum Kit/sounds/tom-2.mp3
  Drum Kit/sounds/tom-3.mp3
  Drum Kit/sounds/tom-4.mp3
  Drum Kit/styles.css
Labels: hacktoberfest-accepted

#167 added an infinite scroll template
  infinite scroll/index.html
  infinite scroll/script.js
  infinite scroll/style.css
Labels: hacktoberfest-accepted

#176 Dice Game Challenge Added
  Dice Game challenge/images/dice1.png
  Dice Game challenge/images/dice2.png
  Dice Game challenge/images/dice3.png
  Dice Game challenge/images/dice4.png
  Dice Game challenge/images/dice5.png
  Dice Game challenge/images/dice6.png
  Dice Game challenge/index.html
  Dice Game challenge/index1.js
  Dice Game challenge/styles1.css
Labels: hacktoberfest-accepted

#178 Tic Tac Toe Game Tampate in Java
  Tic Tac Toe Game Template/Img.jpg
  Tic Tac Toe Game Template/SelectMode.jfif
  Tic Tac Toe Game Template/Tic Tac Toe.iml
  Tic Tac Toe Game Template/backimg.png
  Tic Tac Toe Game Template/out/production/Tic Tac Toe/GamePlay.class
  Tic Tac Toe Game Template/out/production/Tic Tac Toe/SelectMode.class
  Tic Tac Toe Game Template/out/production/Tic Tac Toe/SoloPlay.class
  Tic Tac Toe Game Template/out/production/Tic Tac Toe/TicTacToe.class
  Tic Tac Toe Game Template/src/GamePlay.java
  Tic Tac Toe Game Template/src/SelectMode.java
  Tic Tac Toe Game Template/src/SoloPlay.java
  Tic Tac Toe Game Template/src/TicTacToe.java
Labels: hacktoberfest-accepted

#179 Add files via upload
  playlist-carousel/index.html
  playlist-carousel/script.js
  playlist-carousel/style.css
Labels: hacktoberfest-accepted

#186 portfolio toggle day-night
  Portfolio day-night toggle/book.png
  Portfolio day-night toggle/css-3.png
  Portfolio day-night toggle/github-logo.png
  Portfolio day-night toggle/html.png
  Portfolio day-night toggle/index.html
  Portfolio day-night toggle/java-script.png
  Portfolio day-night toggle/linkedin.png
  Portfolio day-night toggle/main.css
  Portfolio day-night toggle/main.css.map
  Portfolio day-night toggle/main.scss
  Portfolio day-night toggle/mytchnobckgnd.jpg
  Portfolio day-night toggle/script.js
Labels: Under Review

#184 Create memorygame.html
  memorygame.html
Labels: hacktoberfest-accepted

#203 Added react ecommerce page (issue #202)
  E-commerce React/.gitignore
  E-commerce React/README.md
  E-commerce React/package-lock.json
  E-commerce React/package.json
  E-commerce React/public/favicon.ico
  E-commerce React/public/images/k1.jpg
  E-commerce React/public/images/k2.jpg
  E-commerce React/public/images/k3.jpg
  E-commerce React/public/images/k4.jpg
  E-commerce React/public/images/k5.jpg
  E-commerce React/public/images/m1.jpg
  E-commerce React/public/images/m2.jpg
  E-commerce React/public/images/m3.jpg
  E-commerce React/public/images/m4.jpg
  E-commerce React/public/images/m5.jpg
  E-commerce React/public/images/w1.jpg
  E-commerce React/public/images/w2.jpg
  E-commerce React/public/images/w3.jpg
  E-commerce React/public/images/w4.jpg
  E-commerce React/public/images/w5.jpg
  E-commerce React/public/index.html
  E-commerce React/public/logo192.png
  E-commerce React/public/logo512.png
  E-commerce React/public/manifest.json
  E-commerce React/public/robots.txt
  E-commerce React/src/App.css
  E-commerce React/src/App.js
  E-commerce React/src/DUMMY_DATA.js
  E-commerce React/src/Store/cartSlice.js
  E-commerce React/src/Store/index.js
  E-commerce React/src/components/Cart/Cart.module.css
  E-commerce React/src/components/Cart/CartCheckout.js
  E-commerce React/src/components/Cart/CartCheckout.module.css
  E-commerce React/src/components/Cart/CartItem.js
  E-commerce React/src/components/Cart/CartItem.module.css
  E-commerce React/src/components/Cart/Carts.js
  E-commerce React/src/components/Home/Header.js
  E-commerce React/src/components/Home/Header.module.css
  E-commerce React/src/components/Home/HeaderCart.js
  E-commerce React/src/components/Home/HeaderCart.module.css
  E-commerce React/src/components/Home/HomePage.js
  E-commerce React/src/components/Home/Homepage.module.css
  E-commerce React/src/components/Home/ItemList.js
  E-commerce React/src/components/Home/ItemList.module.css
  E-commerce React/src/components/ThankYou.js
  E-commerce React/src/components/ThankYou.module.css
  E-commerce React/src/components/UI/Button.js
  E-commerce React/src/components/UI/Container.js
  E-commerce React/src/components/UI/Input.js
  E-commerce React/src/dfmw.html
  E-commerce React/src/index.css
  E-commerce React/src/index.js
Labels: hacktoberfest-accepted

#197 input text design improved on focus
  sign up form/signup.html
Labels: wontfix
